

export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL';
export const GET_ARTICLE_DETAIL_START = 'GET_ARTICLE_DETAIL_START';
export const GET_ARTICLE_DETAIL_SUCCESS = 'GET_ARTICLE_DETAIL_SUCCESS';
export const GET_ARTICLE_DETAIL_FAIL = 'GET_ARTICLE_DETAIL_FAIL';