export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST';
export const GET_ARTICLE_LIST_START = 'GET_ARTICLE_LIST_START';
export const GET_ARTICLE_LIST_SUCCESS = 'GET_ARTICLE_LIST_SUCCESS';
export const GET_ARTICLE_LIST_FAIL = 'GET_ARTICLE_LIST_FAIL';