

export const GET_HOT_SEARCH  = 'GET_HOT_SEARCH';

export const GET_HOT_SEARCH_START = 'GET_HOT_SEARCH_START';

export const GET_HOT_SEARCH_SUCCESS = 'GET_HOT_SEARCH_SUCCESS';

export const GET_HOT_SEARCH_FAIL = 'GET_HOT_SEARCH_FAIL';